RebeckaOcampoSandgren/HumansVsZombies-Frontend

humansvszombies/package-lock.json, humansvszombies/package.json, humansvszombies/public/index.html, humansvszombies/src/App.css, humansvszombies/src/App.js, humansvszombies/src/Component/GameDetails/GameRegistration.jsx, humansvszombies/src/Component/GameDetails/GameTitle.jsx, humansvszombies/src/Component/LandingPage.jsx, humansvszombies/src/Views/GameDetails.jsx, humansvszombies/src/index.js
Created game details view with game title and registration components
=> feat: created game details page

humansvszombies/src/App.css, humansvszombies/src/Component/GameDetails/GameBiteCode.jsx, humansvszombies/src/Views/GameDetails.jsx
Added bite code part with it's entry.
=> Wip feature add bite code

humansvszombies/src/App.css, humansvszombies/src/Component/GameDetails/GameBiteCode.jsx, humansvszombies/src/Component/GameDetails/GameSquadCreation.jsx, humansvszombies/src/Component/GameDetails/GameSquadDetails.jsx, humansvszombies/src/Component/GameDetails/GameTitle.jsx, humansvszombies/src/Views/GameDetails.jsx
Added a squad creation part with inout for the name and button. Added a list of available squads and a squad details part in detail page
=> Wip feature add sqad list squad creation

humansvszombies/package-lock.json, humansvszombies/package.json, humansvszombies/public/keycloak.json, humansvszombies/public/silent-check-sso.html, humansvszombies/src/App.js, humansvszombies/src/Component/HOC/NavbarLandningPage.jsx, humansvszombies/src/Component/loading/Loading.js, humansvszombies/src/const/roles.js, humansvszombies/src/index.js, humansvszombies/src/keycloak.js, humansvszombies/src/routes/KeycloakRoute.js
App deployed to heroku and with keycloak auth.
=> feat: heroku-keyclock deployment created

humansvszombies/src/Component/LandingPage.jsx
details button enabled if user not logged in through keycloak.
=> feat: auth added to landing page

humansvszombies/.env, humansvszombies/package-lock.json, humansvszombies/package.json, humansvszombies/src/App.css, humansvszombies/src/Component/AdministrationPage.jsx, humansvszombies/src/Component/Administrator/CreateGame.jsx, humansvszombies/src/Component/Administrator/EditGame.jsx, humansvszombies/src/Component/Administrator/EditPlayer.jsx, humansvszombies/src/api/game.js
Split the admin page into smaller components and made the post request for create game work.
=> feat: connected create game to api

humansvszombies/.env, humansvszombies/package-lock.json, humansvszombies/src/Component/Administrator/CreateGame.jsx, humansvszombies/src/Component/Administrator/EditGame.jsx, humansvszombies/src/Component/Administrator/EditPlayer.jsx, humansvszombies/src/api/game.js
connected the edit game in admin view to database (put request)
=> feat: connected edit game to database

humansvszombies/package-lock.json, humansvszombies/package.json, humansvszombies/src/Component/GameCards/Cards.jsx, humansvszombies/src/Component/GameDetails/GameTitle.jsx, humansvszombies/src/Component/WorldMap/GameMap.jsx, humansvszombies/src/Views/GameDetails.jsx
showing selected game by id to game details page
=> Wip feature get game data to gamedetails

humansvszombies/src/api/game.js
=> Wip feature create frontend apis methods

humansvszombies/src/api/player.js, humansvszombies/src/api/squadCheckins.js
Added CRUD methods for player and squadcheckin models
=> Feat: Added CRUD method for squadCheckins and player

humansvszombies/src/api/squadMembers.js
Crud created for squadMember and user
=> feat: Crud created for squadMember and user

humansvszombies/src/Component/Administrator/CreateGame.jsx, humansvszombies/src/Component/HOC/NavbarLandningPage.jsx, humansvszombies/src/api/game.js, humansvszombies/src/api/player.js, humansvszombies/src/api/squadCheckins.js, humansvszombies/src/api/squadMembers.js, humansvszombies/src/api/user.js
=> Wip fix crud api methods

humansvszombies/src/App.css, humansvszombies/src/Component/AdministrationPage.jsx, humansvszombies/src/Component/Administrator/CreateGame.jsx, humansvszombies/src/Component/Administrator/CreateMission.jsx, humansvszombies/src/Component/Administrator/EditGame.jsx, humansvszombies/src/Component/Administrator/EditPlayer.jsx, humansvszombies/src/api/game.js, humansvszombies/src/api/missions.js, humansvszombies/src/api/player.js
Added ability to create a mission for a game and fixed create mission method
=> feat: added create mission to admin page

humansvszombies/src/api/game.js, humansvszombies/src/api/kill.js, humansvszombies/src/api/player.js, humansvszombies/src/api/squad.js, humansvszombies/src/api/squadMembers.js, humansvszombies/src/api/user.js
Added CRUD and reporting methods for kill and squad models
=> Feat: Added CRUD methods for kill and squad models

humansvszombies/src/App.css, humansvszombies/src/Component/AdministrationPage.jsx, humansvszombies/src/Component/Administrator/EditMission.jsx, humansvszombies/src/Component/Administrator/EditPlayer.jsx, humansvszombies/src/api/missions.js
added to both UI and put request for updating missions in database
=> feat: added functionality to edit a mission in a game

humansvszombies/src/Component/Administrator/EditMission.jsx, humansvszombies/src/Component/Administrator/EditPlayer.jsx
checkboxes for bool values instead of textboxes
=> fix: switched to checkboxes

humansvszombies/src/Component/GameDetails/GameSquadCreation.jsx, humansvszombies/src/Views/GameDetails.jsx
Adde squad creation in game details to the database
=> Feat: Added squad creation to the database

humansvszombies/src/App.css, humansvszombies/src/Component/HOC/NavbarLandningPage.jsx
Fixed hover link and put the link on the rigth side.
=> feat: styled navbar

humansvszombies/src/App.js, humansvszombies/src/Component/HOC/NavbarLandningPage.jsx, humansvszombies/src/Component/RenderOnRole.jsx, humansvszombies/src/Views/AdministrationPageView.jsx, humansvszombies/src/Views/GameDetails.jsx, humansvszombies/src/const/roles.js, humansvszombies/src/routes/AdminRoute.jsx, humansvszombies/src/routes/NotAllowed.jsx
Guarded routes based on roles fixed.
=> Feat: Guarded routes fixed

humansvszombies/src/App.css, humansvszombies/src/Component/AdministrationPage.jsx, humansvszombies/src/Component/Administrator/CreateGame.jsx, humansvszombies/src/Component/Administrator/CreateMission.jsx, humansvszombies/src/Component/Administrator/EditGame.jsx, humansvszombies/src/Component/Administrator/EditMission.jsx, humansvszombies/src/Component/Administrator/EditPlayer.jsx, humansvszombies/src/Component/GameCards/Cards.jsx, humansvszombies/src/Component/LandingPage.jsx
Colors of buttons changed in admin page and game cards.
=> feat: changed color of buttons in admin and cards

humansvszombies/src/Component/Administrator/CreateGame.jsx, humansvszombies/src/Component/Administrator/CreateMission.jsx
=> fix: create button and create mission fixed

humansvszombies/src/Component/GameDetails/GameSquadList.jsx, humansvszombies/src/Component/HOC/NavbarLandningPage.jsx, humansvszombies/src/Views/GameDetails.jsx
Show components for users based on their role, Admin or User
=> Feat: Added admin role to the context in game details page

humansvszombies/src/Component/GameDetails/GameSquadList.jsx, humansvszombies/src/Views/GameDetails.jsx, humansvszombies/src/api/game.js, humansvszombies/src/api/kill.js, humansvszombies/src/api/player.js, humansvszombies/src/api/squad.js, humansvszombies/src/api/squadCheckins.js, humansvszombies/src/api/squadMembers.js, humansvszombies/src/api/user.js
Added the functionality of the join button in the game details page for each available squad
=> Feat: added join button to the squad list
